### ISSUE TITLE
where to find LaTex source code for the plasma paper?

### ISSUE THREAD

**Issue by SmartLayer** [ethereum/plasma#4]
Couldn't find it anywhere but the PDF is indeed generated with LaTex.

I wish to encourage translation of the work by sharing it with a few known blockchain paper translators. Besides, there are lots of grammar issues with the paper that needs a clean up in an opensource fashion.

**Comment by chriseth** [comment]
It is here: https://github.com/plasmaio/paper

**Comment by overseers-desk** [comment]
Thanks. Wonder why it is not not in the first page of Google search "plasma ethereum paper github"
